function font_size = new_font_size(varargin)

    if isempty(varargin)
        
        % Default values
        font_size = struct('title', 16, 'legend', 18, 'xlabel', 14,...
                          'ylabel', 16, 'ticklabel', 16);
        
    else        
        font_size = struct(...
            'title',  varargin{1},...
            'legend', varargin{2},...
            'xlabel', varargin{3},...
            'ylabel', varargin{4},...
            'ticklabel', varargin{5});
    end
    
end

